### PR TITLE
fix eating

### PR DESCRIPTION
**Pull request by Driesboy**

### CODE REVIEW

**Comment by thebigsmileXD** [comment]
Uhm.. This does NOT fix eating.. Its for skins!

**Comment by Driesboy** [comment]
Yes skins and eating

**Comment by thebigsmileXD** [comment]
How eating? You don't change anything for eating?

**Comment by Driesboy** [comment]
Oops that is a other pull request
Sorry :)

**Comment by thebigsmileXD** [comment]
Oh ok :D

**Pull request merged**
