### PR TITLE
4th version of de-optimization

### PR DESCRIPTION
**Pull request by PEMapModder**

### CODE REVIEW

**Comment by PEMapModder** [comment]
I recommend you to test it before merging.

**Comment by keithkfng** [comment]
Why do you decline the invitations? Didn't want to commit directly? XD
Now checking with Travis first before merging...

**Comment by PEMapModder** [comment]
One reason is that I don't like this repo. People use this as a forum/chat tool, and it is annoying to get my dashboard spammed.
Can we talk on Gitter?

**Comment by keithkfng** [comment]
Okay.

**Pull request merged**
