### PR TITLE
A Zombie AI Plugin

### PR DESCRIPTION
**Pull request by aodzip**
This work really interesting , the code is interesting too..

### CODE REVIEW

**Comment by thebigsmileXD** [comment]
Do you have the original link too? I would love to check that out. The code looks fine

**Comment by aodzip** [comment]
@thebigsmileXD I can't find the original link . I found it on a publie file share website . But the uploader isn't the author

**Comment by legoboy0215** [comment]
XD MyZombie is very laggy

**Comment by aodzip** [comment]
@legoboy0215 @thebigsmileXD I think we can have a look and make a better mob AI . so i pr this plugin here. But i don't know if this plugin is under GNU GPL

**Comment by legoboy0215** [comment]
If someone plans to do this, add a switch. No one wants AI crap lagging their server.

**Comment by aodzip** [comment]
i agree

**Comment by thebigsmileXD** [comment]
I started with porting Wolf AI from bukkit once.. Not done yet due to lack in api

**Pull request closed without merging**
