### PR TITLE
Patches from other repositories and some from original

### PR DESCRIPTION
**Pull request by keithkfng**
I want at least 5 people to run tests on the skin-patch branch before I merge this.

### CODE REVIEW

**Comment by mwvent** [comment]
Binary.php has no Binary class any more cant run.

**Comment by mwvent** [comment]
Testing using original Binary.php

Found references to AttributeManager
./PocketMine-0.13.0/src/pocketmine/Player__32bit.php:use pocketmine\entity\AttributeManager;
./PocketMine-0.13.0/src/pocketmine/Player__32bit.php:        $this->attribute = new AttributeManager($this);
./PocketMine-0.13.0/src/pocketmine/Player__32bit.php:            $this->getAttribute()->getAttribute(AttributeManager::MAX_HEALTH)->setValue($amount);
./PocketMine-0.13.0/src/pocketmine/Player__32bit.php:        $this->getAttribute()->getAttribute(AttributeManager::MAX_HUNGER)->setValue($amount);
./PocketMine-0.13.0/src/pocketmine/Player__64bit.php:use pocketmine\entity\AttributeManager;
./PocketMine-0.13.0/src/pocketmine/Player__64bit.php:        $this->attribute = new AttributeManager($this);
./PocketMine-0.13.0/src/pocketmine/Player__64bit.php:            $this->getAttribute()->getAttribute(AttributeManager::MAX_HEALTH)->setValue($amount);
./PocketMine-0.13.0/src/pocketmine/Player__64bit.php:        $this->getAttribute()->getAttribute(AttributeManager::MAX_HUNGER)->setValue($amount);

The attributemanager class does not exist (at least not in this branch) - I removed Player__32bit & 64bit to continue test as its not referenced in Player.php

Client hung while connecting, said login timeout - console shows
[00:00:25] [INFO]: tester[/82.16.212.140:19132] logged out due to Login timeout

**Comment by keithkfng** [comment]
Can you fix it?

**Comment by mwvent** [comment]
Ok I've tracked the problem down to LoginPacket.php
It doesn't have a skinflag !

Why does the login timeout - because for some bizzare reason no error is raised when accesing skinflag on the $packet object fails

in player.php under this code
                switch($packet::NETWORK_ID){
                        case ProtocolInfo::LOGIN_PACKET:
                                if($this->loggedIn){
                                        break;
                                }
I added
echo "DEBUG: Next line should be skinflag\n";
echo "DEBUG: " . $packet->skinflag . "\n";

And sure enough when I tried to join the server only the first error shows up

**Comment by mwvent** [comment]
https://github.com/hmy2001/PocketMine-0.13.x/blob/master/src/pocketmine/network/protocol/LoginPacket.php

Can be used as a direct replacement

I can login and see the other players skin!

**Comment by keithkfng** [comment]
@mwvent I've invited you to the team, you can accept the invitation here - https://github.com/ImagicalCorp

**Comment by mwvent** [comment]
Wow thanks :-)

**Comment by mwvent** [comment]
Ok I have committed the changes - just need more people to test the branch now! I'm off to bed will check in tomorrow evening after work

**Comment by keithkfng** [comment]
Yep, alright.

**Comment by Driesboy** [comment]
Can i your team

**Comment by Driesboy** [comment]
Can i join your team

**Comment by Driesboy** [comment]
I have fix 5 bugs

**Pull request closed without merging**
