### PR TITLE
Create Lever.php

### PR DESCRIPTION
**Pull request by ZenaGamingsky**
for the item lever

### CODE REVIEW

**Comment by matcracker** [comment]
Code is wrong.

**Comment by ZenaGamingsky** [comment]
show

**Comment by ZenaGamingsky** [comment]
i fix it

**Comment by DRedDogPE** [comment]
im gonna work on the redstone stuff and this is definatly wrong... 
```php

+	public function onBreak(Item $item){
+		$this->getLevel()->setBlock($this, new Water(), true);
+
+		return true;
+	}
```
Just... what??

**Comment by ZenaGamingsky** [comment]
sorry i just had a code break

**Pull request closed without merging**
