### PR TITLE
Skin patch

### PR DESCRIPTION
**Pull request by keithkfng**
Seems to work better

### CODE REVIEW

**Comment by keithkfng** [comment]
I think this can be merged, someone check and merge it?

**Comment by thebigsmileXD** [comment]
Just one question: does anyone know what the '/' is?

**Comment by kam187** [comment]
What  '/' ?

**Comment by thebigsmileXD** [comment]
Edit: the '\'

**Comment by thebigsmileXD** [comment]
For example before false

**Comment by kam187** [comment]
It means use the root namespace , not any function defined in the local
namespace.

**Comment by thebigsmileXD** [comment]
I don't understand. Why should $test = \false use the root path? Thats.. Hmm

**Comment by kam187** [comment]
If there was a function like say trim that was in the global name space and
you overrode it in the local namespace $test = \trim($x) uses the global
one

$test = trim($x) uses the local one.

I guess true/false could also be overridden with functions so it's probably
just ha not for whoever wrote it.

**Pull request merged**
