### PR TITLE
Fixed Silly Mistakes!!!

### PR DESCRIPTION
**Pull request by Taki21**
Deleted EXTRA "(" and ")"
Fixed Unexpected OBJECT OPERATOR

Should fix issue #188

### CODE REVIEW

**Comment by keithkfng** [comment]
This makes it even worse, according to Travis.

**Comment by Taki21** [comment]
. . . Travis took nearly 10 minutes to give error! Is that normal?

**Comment by Taki21** [comment]
I really just deleted redundant Parentheses btw

**Comment by Taki21** [comment]
and i did nothin wrong to line 510 (error there)

**Comment by keithkfng** [comment]
If it's 10 minutes, that's not normal. It usually takes 1 minute and 30 seconds.

**Comment by Taki21** [comment]
test again?

**Comment by Taki21** [comment]
Get this: 
Call to a member function addIngredient() on null in /home/travis/build/ImagicalCorp/PocketMine-0.13.0/src/pocketmine/inventory/CraftingManager.php on line 510

**Comment by Taki21** [comment]
hmmmm. 10 Minutes Again!!!!

**Comment by Taki21** [comment]
and it says this
No output has been received in the last 10 minutes, this potentially indicates a stalled build or something wrong with the build itself.

**Comment by Skull3x** [comment]
I don't need your fucking shitty ass plugins anymore.

**Comment by Skull3x** [comment]
I don't need your shitty plugins.

**Pull request closed without merging**
