### PR TITLE
Protocol updates from @ Legends of MCPE repo

### PR DESCRIPTION
**Pull request by keithkfng**
Does this fix anything?

### CODE REVIEW

**Comment by mwvent** [comment]
This would break Skins and Login again

**Comment by keithkfng** [comment]
Thanks for the confirmation.

**Comment by mwvent** [comment]
np :-)

**Comment by keithkfng** [comment]
BTW, some people can't build in creative, do you know why?

**Comment by mwvent** [comment]
Not sure - I will have a look though, to start with the hotbar problem was back when I tried to test with the latest branch code. I've put the hotbar fix in the Creative-hotbar-fix. If am lucky enougth to find a fix for the block placing ill use that branch again before removing it

**Comment by keithkfng** [comment]
It might just be because of people not being able to use the creative hot bar. I haven't tested this, this is just a theory.

**Pull request closed without merging**
