### PR TITLE
Experimental redstone items compatibility

### PR DESCRIPTION
**Pull request by keithkfng**
We need at least 3 people test this before merging it. It may cause major damage!

### CODE REVIEW

**Comment by thebigsmileXD** [comment]
The code shows: you don't understand how redstone works -.-"
-powering blocks and getting power out of it again not implemented
-redstone cant power down on slabs, but up

Fix that, i have no time.

**Comment by DRedDogPE** [comment]
@thebigsmileXD I do know how redstone works and i have not fully implimented it yet, this is only a temp solution so basic redstone would work, of course i wont be able to do it all by myself.

**Comment by thebigsmileXD** [comment]
.. Why not checking the bounding box? Or collision.. You could filter out heads, slabs and stairs with that.. And other non solid blocks/solid non powerable ones. What about redstone.. Does a whole wire update in 1 tick? Is the tick rate correct? Do torches invert if redstone wire is on a block and a redstone torch on its side?
Good luck, i just don't like unfinished things to be implemented. You know redstone? Are you in the mood for a challenge? Would love to do one with you on a server or so :D

**Comment by Driesboy** [comment]
can a Join your team plz
i am already create 5 pull request

**Comment by DRedDogPE** [comment]
@thebigsmileXD If you could help out with the code that would be amazing

**Comment by Driesboy** [comment]
i have already helped on this sources
on pocketmine and on github

**Comment by DRedDogPE** [comment]
@Driesboy To do with redstone?

**Comment by Driesboy** [comment]
no

**Comment by SkygridRex** [comment]
very premature xS

**Comment by SkygridRex** [comment]
I could help with the redstone if you want

**Comment by legoboy0215** [comment]
Use Bukkit as an example.

**Comment by thebigsmileXD** [comment]
The bukkit is what i use for mob ai :D

**Comment by PEMapModder** [comment]
So, may I ask, does this branch do anything at all apart from adding items and blocks and tiles declarations?

**Comment by thebigsmileXD** [comment]
Nope xd

**Comment by PEMapModder** [comment]
And then you are telling everyone that you are adding redstone :P

**Comment by thebigsmileXD** [comment]
Yea DUMB implementation

**Comment by legoboy0215** [comment]
Rename it to: Adding Redstone ITEMS

**Comment by rj0495** [comment]
@DRedDogPE Have you got any further on your local files so far? If so can you commit them?

**Comment by thebigsmileXD** [comment]
That crash is not my fault i think

**Comment by thebigsmileXD** [comment]
It passed Travis now

**Comment by keithkfng** [comment]
But we can't merge it... LOL conflicts...

**Comment by thebigsmileXD** [comment]
I wonder which conflicts :confused:

**Comment by PEMapModder** [comment]
Try `git merge remotes/origin/Redstone` and see the conflicts

**Comment by thebigsmileXD** [comment]
# Conflicts:
#	src/pocketmine/block/TrappedChest.php
#	src/pocketmine/item/Item.php
#	src/pocketmine/item/RawRabbit.php

**Comment by PEMapModder** [comment]
Then resolve them manually and commit them.

**Comment by thebigsmileXD** [comment]
I tried, but.. nope, f* that

**Pull request merged**
