### PR TITLE
(Re)fixed the issue where items could not be added to hotbar in creative mode

### PR DESCRIPTION
**Pull request by mwvent**
(Re)fixed the issue where items could not be added to hotbar in creative mode. This was fixed before but overwritten

I take it these changes were reverted by accident and everybody is happy if they are merged back in?

### CODE REVIEW

**Comment by keithkfng** [comment]
Just waiting for Travis CI to confirm the build test.

**Comment by keithkfng** [comment]
Done. I'm happy, but if it doesn't work we can always revert it XD

**Comment by thebigsmileXD** [comment]
Travis does its job?

**Comment by keithkfng** [comment]
Yes, I'm happy with it! Thanks for introducing it!

**Comment by thebigsmileXD** [comment]
Sure. I'll add jenkins too.

**Comment by keithkfng** [comment]
Yay!

**Comment by thebigsmileXD** [comment]
Atleast trying to ;)

**Comment by keithkfng** [comment]
See how you go I love Jenkins XD

**Pull request merged**
