### PR TITLE
This Will Fix Wood Plank Crafting Bug

### PR DESCRIPTION
**Pull request by aodzip**
fix bug:
can't craft plank in crafting table or crafting buggy.

### CODE REVIEW

**Comment by DRedDogPE** [comment]
```php
 		$this->registerRecipe((new ShapedRecipe(Item::get(Item::WOODEN_PLANK, Planks::DARK_OAK, 4),
-			"X"
+			"  ",
+			" X"
 		))->setIngredient("X", Item::get(Item::WOOD2, Wood2::DARK_OAK, 1)));
```
Notice anything weird about this... The metas... Wood2::DARK_OAK and Planks::DARK_OAK

**Comment by aodzip** [comment]
i just foud if u craft planks from crafting table debug will say “unknown shaperecipe”. this can fix the bug. And  replace the shape but i really didn't notice "WOOD2" lol😂😂

**Comment by aodzip** [comment]
I think it should use “Wood”

**Comment by aodzip** [comment]
Finally it works
but i found wood2 leaves2 in pocketmine src 
we can find a way to get ride these files , try to get them into one file?

**Comment by aodzip** [comment]
oh my god i mess the pr up

**Comment by MCPEPIG** [comment]
Wood2 and Wood have different ids. Wood2 is for Acacia and Dark Oak, while Wood is for Oak, Spruce, Birch, & Jungle

**Pull request closed without merging**
