### PR TITLE
PeMapModder set it so

### PR DESCRIPTION
**Pull request by Driesboy**

### CODE REVIEW

**Comment by keithkfng** [comment]
No need.

**Comment by thebigsmileXD** [comment]
Would also say invalid. We discussed about the name. They liked my idea to change it to "IMagicMine" because it contains Imagical Corporation and PocketMine

**Comment by keithkfng** [comment]
How about ImagicalMine that sounds much better XD

**Comment by thebigsmileXD** [comment]
Yea, it does. I like it.

**Pull request closed without merging**
