### PR TITLE
Chest, inventory and skin mega bug fix.

### PR DESCRIPTION
**Pull request by legoboy0215**
Horray!

### CODE REVIEW

**Comment by legoboy0215** [comment]
Anyone verify AGAIN this works?

**Comment by mwvent** [comment]
Skins aren't black but they appear to be cloned? - i.e. two test players with different skins look the same?

**Comment by mwvent** [comment]
Tested again - skins were fine. I think this occasional skin cloning issue has been around since 0.12 anyway?
Chests worked fine for me
Hotbar is still glitchy in creative - I wasn't sure which inventory bug you wanted me to check for though? I tested on Win10 & Android with hotbar sizes 9 & 8 respectively 
Hope this helps :-)

**Comment by legoboy0215** [comment]
Everything is kinda fixed :P

**Comment by legoboy0215** [comment]
Fixed hasPermisson() on null bug by @TahaTheHacker.
No bugs or crashes, eh?

**Comment by legoboy0215** [comment]
What glitch? Hey! At least chests and skins works :)

**Pull request merged**
