### PR TITLE
Update Item.php

### PR DESCRIPTION
**Pull request by ZenaGamingsky**

### CODE REVIEW

**Comment by DRedDogPE** [comment]
Reason?

**Comment by MCPEPIG** [comment]
Please stop with the useless pull requests

**Comment by ZenaGamingsky** [comment]
because

**Comment by ZenaGamingsky** [comment]
new item
and 215 has no redston or lamps levers fix it

**Comment by ZenaGamingsky** [comment]
i now fixed it

**Comment by keithkfng** [comment]
Seriously, I'm closing this PR. 
1. More descriptive title. 
2. Explain what you did in the description
If your PR doesn't match criteria, it'll be closed.

**Pull request closed without merging**
