### PR TITLE
Redstone PR #1

### PR DESCRIPTION
**Pull request by MCPEPIG**

### CODE REVIEW

**Comment by DRedDogPE** [comment]
Lever, Redstone Torch, Buttons??

**Comment by MCPEPIG** [comment]
Erm yeah...

**Comment by legoboy0215** [comment]
Repopen in the future. Why redstone when some stuff are not fixed?

**Comment by keithkfng** [comment]
Leave this open - but don't merge it YET.

**Comment by Driesboy** [comment]
? You remove the sound

**Comment by keithkfng** [comment]
What sound?

**Comment by Driesboy** [comment]
Drapdoor sound

**Comment by Driesboy** [comment]
https://github.com/MCPEPIG/PocketMine-0.13.0/commit/5a41cce3a7914d1b924fc6bcb89141c5f09262fb

**Comment by MCPEPIG** [comment]
That's iron trapdoor...

**Comment by Driesboy** [comment]
Ok

**Comment by matcracker** [comment]
For merge it you must add class for each items you add in this PR, so Buttons class, lever, etc..

**Comment by DRedDogPE** [comment]
Im going to work on the redstone stuff later today

**Comment by MCPEPIG** [comment]
Alright @DRedDogPE

**Comment by DRedDogPE** [comment]
@MCPEPIG Feel free to help lol, look at the redstone branch

**Comment by MCPEPIG** [comment]
I saw it already ;)

**Comment by DRedDogPE** [comment]
ok

**Pull request closed without merging**
