### PR TITLE
Removed backslash for top NS constants and function calls

### PR DESCRIPTION
**Pull request by PEMapModder**

### CODE REVIEW

**Comment by PEMapModder** [comment]
Wait, still not working

**Comment by keithkfng** [comment]
I invited you to the organisation twice, you probably declined the invitations XD

**Comment by PEMapModder** [comment]
Yep

**Comment by keithkfng** [comment]
I remember you saying to @DRedDogPE that removing backslashes was bad practice? Something like that...

**Comment by PEMapModder** [comment]
@keithkfng something like that should be done in releases like how @PocketMine team did with https://github.com/PocketMine/Preprocessor, not in the code directly

**Pull request closed without merging**
